-- Adicionando campo 'active' com valor padrão TRUE para não impactar dados existentes
ALTER TABLE tb_users ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_profiles ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_categories ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_courses ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_topics ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_replies ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
