spring:
  application:
    name: app

  mvc:
    servlet:
      path: /api/v1

  datasource:
    url: jdbc:postgresql://localhost:5432/db-forum-hub
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

